DROP USER questionProg CASCADE;
CREATE USER questionProg
IDENTIFIED BY qmpassword
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;
GRANT CONNECT TO questionProg;
GRANT RESOURCE TO questionProg;
GRANT CREATE SESSION TO questionProg;
GRANT CREATE TABLE TO questionProg;
GRANT CREATE VIEW TO questionProg;
conn questionProg/qmpassword;
/************************************
Tables and sequences
************************************/

CREATE SEQUENCE QMS_Users_seq;
CREATE TABLE QMS_Users (
    USER_ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(32) UNIQUE,
    USER_PW VARCHAR2(32) NOT NULL,
    USER_ROLE NUMBER NOT NULL
);

CREATE SEQUENCE QMS_Questions_seq;
CREATE TABLE QMS_Questions (
    QUESTION_ID NUMBER PRIMARY KEY,
    QUESTION_PROBLEM VARCHAR2(400) NOT NULL,
    QUESTION_CORRECT VARCHAR2(400) NOT NULL,
    QUESTION_WRONG1 VARCHAR2(400) NOT NULL,
    QUESTION_WRONG2 VARCHAR2(400),
    QUESTION_WRONG3 VARCHAR2(400),
    QUESTION_EXPLANATION VARCHAR2(400),
    QUESTION_CREATOR NUMBER,
    CONSTRAINT QUESTION_CREATOR_FK FOREIGN KEY(QUESTION_CREATOR) REFERENCES QMS_Users(USER_ID)
);

CREATE SEQUENCE QMS_Quizzes_seq;
CREATE TABLE QMS_Quizzes (
    QUIZ_ID NUMBER PRIMARY KEY,
    QUIZ_NAME VARCHAR2(32),
    QUIZ_CREATOR NUMBER,
    CONSTRAINT QUIZ_CREATOR_FK FOREIGN KEY(QUIZ_CREATOR) REFERENCES QMS_Users(USER_ID)
);

CREATE TABLE QMS_Grades (
    USER_ID NUMBER REFERENCES QMS_Users(USER_ID),
    QUIZ_ID NUMBER REFERENCES QMS_Quizzes(QUIZ_ID),
    QUESTION_ID NUMBER REFERENCES QMS_Questions(QUESTION_ID),
    GRADE DECIMAL(4,2),
    CHOICE VARCHAR2(400),
    ATTEMPT_NUMBER NUMBER
);

CREATE TABLE QMS_Quiz_Assignment (
    USER_ID NUMBER REFERENCES QMS_Users(USER_ID),
    QUIZ_ID NUMBER REFERENCES QMS_Quizzes(QUIZ_ID),
    MAX_ATTEMPTS NUMBER DEFAULT 3,
    CURRENT_ATTEMPTS NUMBER DEFAULT 0
);


CREATE TABLE QMS_Quiz_Question (
    QUESTION_ID NUMBER,
    QUIZ_ID NUMBER, 
    CONSTRAINT QUESTION_ID_FK FOREIGN KEY(QUESTION_ID) REFERENCES QMS_Questions(QUESTION_ID),
    CONSTRAINT QUIZ_ID_FK FOREIGN KEY(QUIZ_ID) REFERENCES QMS_Quizzes(QUIZ_ID)
);
/**********************************
*       Insert Table Values       *
**********************************/
-- Insert User
INSERT INTO QMS_Users VALUES (1,'a','a',1);
INSERT INTO QMS_Users VALUES (2,'test','test',0);

Insert INTO QMS_Questions VALUES (101, 'PROBLEM', 'CORRECT SOLUTION', 'WRONG1', 'WRONG2', 'WRONG3', 'BECAUSE', 1);
Insert INTO QMS_Questions VALUES (102, 'PROBLEM2', 'CORRECT SOLUTION', 'WRONG1', 'WRONG2', 'WRONG3', 'BECAUSE', 1);
Insert INTO QMS_Questions VALUES (103, 'PROBLEM3', 'CORRECT SOLUTION', 'WRONG1', 'WRONG2', 'WRONG3', 'BECAUSE', 1);

Insert INTO QMS_Quizzes VALUES (301, 'GOOD QUIZ', 1);

Insert INTO QMS_Quiz_Question VALUES (101, 301);
Insert INTO QMS_Quiz_Question VALUES (102, 301);
Insert INTO QMS_Quiz_Question VALUES (103, 301);

Insert INTO QMS_Quiz_Assignment VALUES (2, 301);

commit;