DROP USER questionProg CASCADE;
CREATE USER questionProg
IDENTIFIED BY qmpassword
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;
GRANT CONNECT TO questionProg;
GRANT RESOURCE TO questionProg;
GRANT CREATE SESSION TO questionProg;
GRANT CREATE TABLE TO questionProg;
GRANT CREATE VIEW TO questionProg;
conn questionProg/qmpassword;
/************************************
Tables and sequences
************************************/

CREATE SEQUENCE QMS_Users_seq;
CREATE TABLE QMS_Users (
    USER_ID NUMBER PRIMARY KEY,
    USER_NAME VARCHAR2(32) UNIQUE,
    USER_PW VARCHAR2(32) NOT NULL,
    USER_ROLE NUMBER NOT NULL
);

CREATE SEQUENCE QMS_Questions_seq;
CREATE TABLE QMS_Questions (
    QUESTION_ID NUMBER PRIMARY KEY,
    QUESTION_PROBLEM VARCHAR2(400) NOT NULL,
    QUESTION_CORRECT VARCHAR2(400) NOT NULL,
    QUESTION_WRONG1 VARCHAR2(400) NOT NULL,
    QUESTION_WRONG2 VARCHAR2(400),
    QUESTION_WRONG3 VARCHAR2(400),
    QUESTION_EXPLANATION VARCHAR2(400),
    QUESTION_CREATOR NUMBER,
    CONSTRAINT QUESTION_CREATOR_FK FOREIGN KEY(QUESTION_CREATOR) REFERENCES QMS_Users(USER_ID)
);

CREATE SEQUENCE QMS_Quizzes_seq;
CREATE TABLE QMS_Quizzes (
    QUIZ_ID NUMBER PRIMARY KEY,
    QUIZ_NAME VARCHAR2(32),
    QUIZ_CREATOR NUMBER,
    CONSTRAINT QUIZ_CREATOR_FK FOREIGN KEY(QUIZ_CREATOR) REFERENCES QMS_Users(USER_ID)
);

CREATE TABLE QMS_Grades (
    USER_ID NUMBER REFERENCES QMS_Users(USER_ID),
    QUIZ_ID NUMBER REFERENCES QMS_Quizzes(QUIZ_ID),
    GRADE DECIMAL(4,2),
    ANS_001 NUMBER,
    ANS_002 NUMBER,
    ANS_003 NUMBER,
    ANS_004 NUMBER,
    ANS_005 NUMBER,
    ANS_006 NUMBER,
    ANS_007 NUMBER,
    ANS_008 NUMBER,
    ANS_009 NUMBER,
    ANS_010 NUMBER,
    ANS_011 NUMBER,
    ANS_012 NUMBER,
    ANS_013 NUMBER,
    ANS_014 NUMBER,
    ANS_015 NUMBER,
    ANS_016 NUMBER,
    ANS_017 NUMBER,
    ANS_018 NUMBER,
    ANS_019 NUMBER,
    ANS_020 NUMBER,
    ANS_021 NUMBER,
    ANS_022 NUMBER,
    ANS_023 NUMBER,
    ANS_024 NUMBER,
    ANS_025 NUMBER,
    ANS_026 NUMBER,
    ANS_027 NUMBER,
    ANS_028 NUMBER,
    ANS_029 NUMBER,
    ANS_030 NUMBER,
    ANS_031 NUMBER,
    ANS_032 NUMBER,
    ANS_033 NUMBER,
    ANS_034 NUMBER,
    ANS_035 NUMBER,
    ANS_036 NUMBER,
    ANS_037 NUMBER,
    ANS_038 NUMBER,
    ANS_039 NUMBER,
    ANS_040 NUMBER,
    ANS_041 NUMBER,
    ANS_042 NUMBER,
    ANS_043 NUMBER,
    ANS_044 NUMBER,
    ANS_045 NUMBER,
    ANS_046 NUMBER,
    ANS_047 NUMBER,
    ANS_048 NUMBER,
    ANS_049 NUMBER,
    ANS_050 NUMBER,
    ANS_051 NUMBER,
    ANS_052 NUMBER,
    ANS_053 NUMBER,
    ANS_054 NUMBER,
    ANS_055 NUMBER,
    ANS_056 NUMBER,
    ANS_057 NUMBER,
    ANS_058 NUMBER,
    ANS_059 NUMBER,
    ANS_060 NUMBER,
    ANS_061 NUMBER,
    ANS_062 NUMBER,
    ANS_063 NUMBER,
    ANS_064 NUMBER,
    ANS_065 NUMBER,
    ANS_066 NUMBER,
    ANS_067 NUMBER,
    ANS_068 NUMBER,
    ANS_069 NUMBER,
    ANS_070 NUMBER,
    ANS_071 NUMBER,
    ANS_072 NUMBER,
    ANS_073 NUMBER,
    ANS_074 NUMBER,
    ANS_075 NUMBER,
    ANS_076 NUMBER,
    ANS_077 NUMBER,
    ANS_078 NUMBER,
    ANS_079 NUMBER,
    ANS_080 NUMBER,
    ANS_081 NUMBER,
    ANS_082 NUMBER,
    ANS_083 NUMBER,
    ANS_084 NUMBER,
    ANS_085 NUMBER,
    ANS_086 NUMBER,
    ANS_087 NUMBER,
    ANS_088 NUMBER,
    ANS_089 NUMBER,
    ANS_090 NUMBER,
    ANS_091 NUMBER,
    ANS_092 NUMBER,
    ANS_093 NUMBER,
    ANS_094 NUMBER,
    ANS_095 NUMBER,
    ANS_096 NUMBER,
    ANS_097 NUMBER,
    ANS_098 NUMBER,
    ANS_099 NUMBER,
    ANS_100 NUMBER
);

CREATE TABLE QMS_Quiz_Assignment (
    USER_ID NUMBER REFERENCES QMS_Users(USER_ID),
    QUIZ_ID NUMBER REFERENCES QMS_Quizzes(QUIZ_ID),
    MAX_ATTEMPTS NUMBER DEFAULT 3,
    CURRENT_ATTEMPTS NUMBER DEFAULT 0
);


CREATE TABLE QMS_Quiz_Question (
    QUESTION_ID NUMBER,
    QUIZ_ID NUMBER, 
    CONSTRAINT QUESTION_ID_FK FOREIGN KEY(QUESTION_ID) REFERENCES QMS_Questions(QUESTION_ID),
    CONSTRAINT QUIZ_ID_FK FOREIGN KEY(QUIZ_ID) REFERENCES QMS_Quizzes(QUIZ_ID)
);
/**********************************
*       Insert Table Values       *
**********************************/
-- Insert User
INSERT INTO QMS_Users VALUES (1,'a','a',1);
INSERT INTO QMS_Users VALUES (2,'test','test',0);

Insert INTO QMS_Questions VALUES (101, 'PROBLEM', 'CORRECT SOLUTION', 'WRONG1', 'WRONG2', 'WRONG3', 'BECAUSE', 1);
Insert INTO QMS_Questions VALUES (102, 'PROBLEM2', 'CORRECT SOLUTION', 'WRONG1', 'WRONG2', 'WRONG3', 'BECAUSE', 1);
Insert INTO QMS_Questions VALUES (103, 'PROBLEM3', 'CORRECT SOLUTION', 'WRONG1', 'WRONG2', 'WRONG3', 'BECAUSE', 1);

commit;